#!/bin/bash -e
# =====================================================================
#     #######  #####          #     #   ###   #     # #     #   ###
#     #       #     #         #     #    #    ##    # ##    #    #
#     #       #               #     #    #    # #   # # #   #    #
#      #####  #  ####  #####  #     #    #    #  #  # #  #  #    #
#           # #     #          #   #     #    #   # # #   # #    #
#     #     # #     #           # #      #    #    ## #    ##    #
#      #####   #####             #      ###   #     # #     #   ###
# =====================================================================
#
# SimulaMet OpenAirInterface Evolved Packet Core VNF and NS
# Copyright (C) 2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ====== Build ==============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Building ...\x1b[0m"
make

#osm ns delete 
#osm vnf-delete


# ====== Clean up ===========================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Deleting existing setup ...\x1b[0m"
osm vnfd-delete SimulaMet-OAI-EPC_vnfd || true
osm nsd-delete SimulaMet-OAI-EPC_nsd || true


# ====== Create =============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Creating ...\x1b[0m"
osm vnfd-create SimulaMet-OAI-EPC_vnfd.tar.gz
osm nsd-create SimulaMet-OAI-EPC_nsd.tar.gz 


# ====== Instantiate ========================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Instantiating ...\x1b[0m"
osm ns-create \
   --ns_name SimulaMet-OAI-EPC \
   --nsd_name SimulaMet-OAI-EPC_nsd \
   --vim_account openstack-site \
   --ssh_keys ~/.ssh/id_rsa.pub
# --config '{vld: [ {name: mgmtnet, vim-network-name: osm-ext} ] }'


# ====== Done! ==============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Done!\x1b[0m"
