#!/bin/bash -e
# =====================================================================
#     #######  #####          #     #   ###   #     # #     #   ###
#     #       #     #         #     #    #    ##    # ##    #    #
#     #       #               #     #    #    # #   # # #   #    #
#      #####  #  ####  #####  #     #    #    #  #  # #  #  #    #
#           # #     #          #   #     #    #   # # #   # #    #
#     #     # #     #           # #      #    #    ## #    ##    #
#      #####   #####             #      ###   #     # #     #   ###
# =====================================================================
#
# SimulaMet OpenAirInterface Evolved Packet Core VNF and NS
# Copyright (C) 2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

NS="hackfest_proxycharm"
VNFD="${NS}_vnfd"
NSD="${NS}_nsd"


# ====== Build ==============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Building ...\x1b[0m"
cmake .
make


# ====== Clean up ===========================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Deleting existing setup ...\x1b[0m"
osm ns-delete --wait ${NS} || true
osm nsd-delete ${NSD} || true
osm vnfd-delete ${VNFD} || true


# ====== Create =============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Creating ...\x1b[0m"
osm vnfd-create ${VNFD}.tar.gz
osm nsd-create ${NSD}.tar.gz


# ====== Instantiate ========================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Instantiating ...\x1b[0m"
if [ -e params.yaml ] ; then
   config_file_option=" --config_file params.yaml"
else
   echo >&2 "WARNING: No configuration file params.yaml found!"
   config_file_option=""
fi
osm ns-create \
   --ns_name ${NS} \
   --nsd_name ${NSD} \
   --config_file params.yaml \
   --vim_account openstack-site \
   --ssh_keys ~/.ssh/id_rsa.pub
# --config '{vld: [ {name: mgmtnet, vim-network-name: osm-ext} ] }'


# ====== Done! ==============================================================
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Done!\x1b[0m"

# osm ns-list --filter=name=${NS}
id=`osm ns-list --filter=name=${NS} | grep "| ${NS}" | awk '{ print $4 }'`
echo "ID=${id}"
sleep 10
echo "juju switch ${id}"
juju switch ${id}
