#!/bin/sh

juju show-action-status |grep -B3 -A1 fail | tee juju.errors
IDs=`grep "^  id:" juju.errors | cut -d':' -f2 | tr -d '" \t'`
for id in $IDs ; do
   echo "===> juju show-action-output $id"
done
