#!/bin/bash -e
# =====================================================================
#     #######  #####          #     #   ###   #     # #     #   ###
#     #       #     #         #     #    #    ##    # ##    #    #
#     #       #               #     #    #    # #   # # #   #    #
#      #####  #  ####  #####  #     #    #    #  #  # #  #  #    #
#           # #     #          #   #     #    #   # # #   # #    #
#     #     # #     #           # #      #    #    ## #    ##    #
#      #####   #####             #      ###   #     # #     #   ###
# =====================================================================
#
# SimulaMet OpenAirInterface Evolved Packet Core VNF and NS
# Copyright (C) 2019-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

rm -f juju.errors
juju show-action-status |grep -B3 -A1 fail | tee juju.errors
echo ""

cat juju.errors | tr -d '" \t' | (
   action="???"
   id="???"
   IFS=":"
   while read key value ; do
      if [ "$key" == "-action" ]; then
         action="$value"
      elif [ "$key" == "id" ] ; then
         id="$value"
      elif [ "$key" == "unit" ] ; then
         if [ "$action" != "verify-ssh-credentials" ] ; then
            unit="$value"
            echo -e "\x1b[31m###### Action $action in Unit $unit failed, ID $id ######\x1b[0m"
            echo -e "\x1b[36m===> juju show-action-output $id\x1b[0m"
            echo -en "\x1b[34m"
            juju show-action-output $id
            echo -e "\x1b[0m"
         fi
         action="???"
         id="???"
      # else
      #    echo "KEY $key"
      fi
   done
)
