#!/bin/bash -e
# =================================================================
#          #     #                 #     #
#          ##    #   ####   #####  ##    #  ######   #####
#          # #   #  #    #  #    # # #   #  #          #
#          #  #  #  #    #  #    # #  #  #  #####      #
#          #   # #  #    #  #####  #   # #  #          #
#          #    ##  #    #  #   #  #    ##  #          #
#          #     #   ####   #    # #     #  ######     #
#
#       ---   The NorNet Testbed for Multi-Homed Systems  ---
#                       https://www.nntb.no
# =================================================================
#
# Copy Mosaic5G repositories
# Copyright (C) 2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

OLD_SERVER="https://gitlab.eurecom.fr/"
NEW_SERVER_GIT="git@github.com:simula/mosaic5g-"
NEW_SERVER_HTTPS="https://github.com/simula/mosaic5g-"
REPOSITORIES="mosaic5g/mosaic5g flexran/flexran-rtc  mosaic5g/jox  mosaic5g/kube5g  mosaic5g/ll-mec  oai/openair-cn  oai/openairinterface5g  mosaic5g/store  mosaic5g/ll-mec-ovs"

WORKDIR=`pwd`/tmp
mkdir -p ${WORKDIR}

cd ${WORKDIR}
mkdir -p flexran mosaic5g oai


# ====== Mirror all repositories ============================================
for repository in ${REPOSITORIES} ; do
   echo ""
   echo "###### ${repository} ######"

   if [ ! -e ${repository}.mirror ] ; then
      git clone -q --mirror ${OLD_SERVER}${repository}.git ${repository}.mirror
   else
      cd ${repository}.mirror
      git fetch -q --all
      cd ${WORKDIR}
   fi

   cd ${repository}.mirror

   echo "==== Updating repository URL ===="
   newRepository=`echo "${repository}" | sed -e "s#.*/##g"`
   git remote set-url origin ${NEW_SERVER_GIT}${newRepository}.git

   echo "==== Push ===="
   git push --mirror || true
   cd ${WORKDIR}

done


# ====== Update submodule URLs in main repository ===========================
for repository in mosaic5g/mosaic5g ; do
   echo ""
   echo "###### ${repository} ######"

   if [ ! -e ${repository} ] ; then
      newRepository=`echo "${repository}" | sed -e "s#.*/##g"`
      git clone -q ${NEW_SERVER_GIT}${newRepository}.git ${repository}
   else
      cd ${repository}
      git fetch -q --all
      cd ${WORKDIR}
   fi

   cd ${repository}

   if [ -e .gitmodules ] ; then
      echo "==== Updating submodule URLs ===="
      sed -e "s#url = ${OLD_SERVER}\(mosaic5g/\|oai/\|flexran/\)#url = ${NEW_SERVER_HTTPS}#g" -i .gitmodules && \
         git commit -m "Updated submodule URLs" .gitmodules && \
         git push
   fi

   cd ${WORKDIR}
done
