#!/bin/bash -e

mkdir -p src
cd src

if [ ! -d oai-cn5g-fed ] ; then
   git clone https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed.git
fi

sudo sysctl net.ipv4.conf.all.forwarding=1
sudo iptables -P FORWARD ACCEPT
