#!/bin/bash -e

export RELEASE=ReleaseTWELVE
export REPOSITORY=stable
export DOCKER_TAG=12

sudo apt install -y colordiff git snapd curl

cd ~
rm -f install_osm.sh
wget https://osm-download.etsi.org/ftp/osm-12.0-twelve/install_osm.sh
chmod +x install_osm.sh
./install_osm.sh -y 2>&1 | tee osm_install_log.txt
# !!! WITHOUT: --k8s_monitor
# !!! To be installed later with script "add-k8s_monitoring" !!!


echo "###### Installing \"charm\" snap"
sudo snap install charm --classic

echo "###### Installing OSM IM"
sudo add-apt-repository -y "deb [arch=amd64] https://osm-download.etsi.org/repository/osm/debian/${RELEASE} ${REPOSITORY} IM"
sudo apt-get update
sudo apt-get install -y python3-osm-im

echo "###### Adding Python packages"
sudo apt install -y cmake yamllint

echo "###### Adding VIM"
~/vim
