#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import traceback



class Test:
   def __init__(self):
      import ipaddress
      self.ipaddress_module = ipaddress

   def test(self):
      a = self.ipaddress_module.IPv4Address('1.2.3.4')
      print('Test: ' + str(a))



t1 = Test()
t1.test()
