#!/bin/bash

ps ax | grep http.server | grep python | grep 3003 | awk '{ print $1 }' | xargs -r kill
sleep 2
cd http
yamllint -d '{extends: default, rules: {document-start: {present: no}, line-length: {max: 4096}, comments-indentation: disable}}' user-data
python3 -m http.server 3003 &
cd ..


LOCATION=~/Nedlastinger/ubuntu-18.04.5-live-server-amd64.iso
# LOCATION=~/Nedlastinger/ubuntu-20.04.1-live-server-amd64.iso
# LOCATION=~/Nedlastinger/groovy-live-server-amd64.iso

name=Test
size=`echo "32*(1024^3) + 16896" | bc`
image=image.qcow


virsh destroy "${name}"          >/dev/null 2>&1
virsh undefine --nvram "${name}" >/dev/null 2>&1


rm -f ${image}
qemu-img create -f qcow2 -o size=${size},nocow=on ${image}


bootOptions="--boot uefi"
osOptions="--os-type linux --os-variant ubuntu20.04"

virt-install \
   --quiet \
   --name "${name}" \
   --vcpus 4 \
   --cpu host \
   --ram 4096 \
   --video virtio --channel spicevmc \
   --controller scsi,model=virtio-scsi,driver.iommu=on \
   --disk "bus=scsi,path=${image},format=qcow2,cache=unsafe,discard=unmap" \
   ${bootOptions} ${osOptions} \
   --location "${LOCATION},kernel=casper/vmlinuz,initrd=casper/initrd" \
   --extra-args "autoinstall ds=nocloud-net;seedfrom=http://_gateway:3003/" \
   --noreboot


#    ,kernel=casper/hwe-vmlinuz,initrd=casper/hwe-initrd" \

#    --extra-args "priority=critical preseed/file=/legacy.cfg" \
#    --extra-args "priority=critical preseed/url=http://_gateway:3003/legacy.cfg" \
