#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e


HYPERVISOR="VirtualBox"
UBUNTU="20.04"

HOSTNAME="albacete.openstack"
USER_NAME="nornetpp"
USER_PASSWORD="osm4us"
USER_REALNAME="NorNet Praesum Presum"

# ====== Build VMs ==========================================================
for ubuntu in ${UBUNTU} ; do
   ./make-vm -H ${HYPERVISOR} \
      --project 5gVINNI-OpenStack --distribution Ubuntu --release ${ubuntu} \
      --hostname "${HOSTNAME}" \
      --username "${USER_NAME}" --realname "${USER_REALNAME}" --password "${USER_PASSWORD}" \
      -1
done
wait
