#!/bin/bash

vm_name="VirtualBox-Template-Ubuntu-Server-20.04-LTS"
vm_description='NorNet VM Template'
vm_version=`date +"%Y.%m.%d-%H%M%S"`
vm_disk_root=32768
vm_disk_home=131072
vm_disk_swap=4096

sudo service virtualbox start
sudo service vboxdrv start

packer build \
   -var "vm_name=${vm_name}"             \
   -var "vm_version=${vm_version}"       \
   -var "vm_version=${vm_version}"       \
   -var "vm_disk_root=${vm_disk_root}"   \
   -var "vm_disk_home=${vm_disk_home}"   \
   -var "vm_disk_swap=${vm_disk_swap}"   \
   virtualbox.json
