#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e


HYPERVISOR="QEMU"   # "VirtualBox"
DISTRIBUTION="Ubuntu"
RELEASES="16.04-LTS 18.04-LTS 20.04-LTS"
# RELEASES="18.04-LTS"


PROJECTS="5gVINNI-OpenStack-Development"   # 5gVINNI-OpenStack"
HOSTNAME="albacete.openstack"
USER_NAME="nornetpp"
USER_PASSWORD="osm4us"
USER_REALNAME="NorNet Praesum Presum"


# ====== Build VMs ==========================================================
for project in ${PROJECTS} ; do
   for release in ${RELEASES} ; do
      (
         name="${HYPERVISOR}-${project}-${DISTRIBUTION}-${release}"
         logfile="${name}.log"
         startTime=`date`
         echo "${startTime}: Starting to build ${name} ..."
         if ./make-vm -H ${HYPERVISOR} \
               --project ${project} --distribution ${DISTRIBUTION} --release ${release} \
               --hostname "${HOSTNAME}" \
               --username "${USER_NAME}" --realname "${USER_REALNAME}" --password "${USER_PASSWORD}" \
               -1 --root 12288   >${logfile} 2>&1 ; then
            result="OK"
         else
            result="FAILED!"
         fi
         finishTime=`date`
         echo "${startTime}: Finished to build ${name} - ${result} -> ${logfile}"
      ) &
   done
done
wait
