#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e


HYPERVISOR="VirtualBox"
UBUNTU="16.04 18.04 20.04"


# ====== Build VMs ==========================================================
for ubuntu in ${UBUNTU} ; do
   ./make-vm -H ${HYPERVISOR} -P 5gVINNI-OpenStack -D Ubuntu -R ${ubuntu} -1   &
done
wait
