#!/bin/bash

DESTINATION="nornetpp@odin.simula.nornet:images/"
SSH_PROXY="oesthorn.nntb.no"

imageFiles=""
VMs=`find . -mindepth 1 -maxdepth 1 -type d -name "QEMU*OpenStack*"`
for vm in ${VMs} ; do
   pushd ${vm} >/dev/null
   if [ -e "successfully-built.txt" ] ; then
      imageDirectory=`find . -mindepth 1 -maxdepth 1 -type d -name "*OpenStack*"`
      if [ -d "${imageDirectory}" ] ; then
         pushd ${imageDirectory} >/dev/null
         image=`ls -S .`
         if [ -e "${image}" ] ; then
            sh -c "rsync -e \"ssh -J ${SSH_PROXY}\" -Pv --partial  ${image} ${DESTINATION}${image}.qcow2"
            imageFiles="${imageFiles} ${image}.qcow2"
         fi
         popd >/dev/null
      fi
   fi
   popd >/dev/null
done


echo ""
echo "------ OpenStack commands: ------"
for imageFile in ${imageFiles} ; do
   imageName="${imageFile/.qcow2/}"
   echo "image delete ${imageName}"
   echo "image create ${imageName} --file images/${imageFile} --disk-format qcow2 --container-format bare --property hw_firmware_type=uefi --property architecture=amd64 --public"
done
