#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# NOTE:
# The following environment variables are expected:
# - USER_NAME
# - BACKGROUND_SDDM
# - BACKGROUND_LOCKSCREEN
# - BACKGROUND_DESKTOP


# ###### NorNet Desktop package installation ################################

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then
   /usr/bin/apt-get update

   packages="nornet-display sddm kde-style-oxygen-qt5 gtk2-engines-oxygen plasma-theme-oxygen oxygen-cursor-theme oxygen-cursor-theme-extra oxygen-icon-theme oxygen-sounds"

   # Try 3 times, for the case of download issues:
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages} || \
      sleep 30 && env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages} || \
         sleep 30 && env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y nornet-display sddm @KDE qt5-style-oxygen oxygen-gtk2 plasma-oxygen oxygen-icon-theme oxygen-cursor-themes oxygen-sound-theme oxygen-fonts firefox

   servicectl enable sddm.service
   servicectl start sddm.service
fi


# ###### NorNet Desktop configuration #######################################

# ====== Make directories ===================================================
mkdir -p /home/${USER_NAME}/.config
mkdir -p /home/${USER_NAME}/.local


# ====== Desktop configuration ==============================================
cat >/home/${USER_NAME}/.config/kscreenlockerrc <<EOF
[\$Version]
update_info=kscreenlocker.upd:0.1-autolock

[Greeter][Wallpaper][org.kde.image][General]
Image=file://${BACKGROUND_LOCKSCREEN}
EOF


cat >/home/${USER_NAME}/.config/kactivitymanagerdrc <<EOF
[activities]
6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788=Default

[main]
currentActivity=6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788
EOF


cat >/home/${USER_NAME}/.config/plasma-org.kde.plasma.desktop-appletsrc <<EOF
[ActionPlugins][0]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu
wheel:Vertical;NoModifier=org.kde.switchdesktop

[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
ItemGeometriesHorizontal=
activityId=6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][1][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Configuration]
PreloadWeight=10

[Containments][1][General]
ToolBoxButtonState=topcenter
ToolBoxButtonX=739

[Containments][1][Wallpaper][org.kde.image][General]
Image=file://${BACKGROUND_DESKTOP}

[Containments][2]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][2][Applets][21]
immutability=1
plugin=org.kde.plasma.systemloadviewer

[Containments][2][Applets][21][Configuration]
PreloadWeight=42

[Containments][2][Applets][22]
immutability=1
plugin=org.kde.plasma.icon

[Containments][2][Applets][22][Configuration]
PreloadWeight=42
localPath=/home/nornetpp/.local/share/plasma_icons/firefox.desktop
url=file:///usr/share/applications/firefox.desktop

[Containments][2][Applets][23]
immutability=1
plugin=org.kde.plasma.icon

[Containments][2][Applets][23][Configuration]
PreloadWeight=42
localPath=/home/nornetpp/.local/share/plasma_icons/org.kde.konsole.desktop
url=file:///usr/share/applications/org.kde.konsole.desktop

[Containments][2][Applets][3]
immutability=1
plugin=org.kde.plasma.kickoff

[Containments][2][Applets][3][Configuration]
PreloadWeight=92

[Containments][2][Applets][3][Configuration][Configuration/General]
showAppsByName=true

[Containments][2][Applets][3][Configuration][General]
favorites=preferred://browser,org.kde.discover.desktop,org.kde.kontact.desktop,org.kde.kate.desktop,libreoffice-startcenter.desktop,org.kde.dolphin.desktop,org.kde.ksysguard.desktop,systemsettings.desktop,org.kde.konsole.desktop
favoritesPortedToKAstats=true

[Containments][2][Applets][3][Configuration][Shortcuts]
global=Alt+F1

[Containments][2][Applets][3][Shortcuts]
global=Alt+F1

[Containments][2][Applets][4]
immutability=1
plugin=org.kde.plasma.pager

[Containments][2][Applets][4][Configuration]
PreloadWeight=10

[Containments][2][Applets][5]
immutability=1
plugin=org.kde.plasma.taskmanager

[Containments][2][Applets][5][Configuration]
PreloadWeight=10

[Containments][2][Applets][6]
immutability=1
plugin=org.kde.plasma.systemtray

[Containments][2][Applets][6][Configuration]
PreloadWeight=10
SystrayContainmentId=7

[Containments][2][Applets][8]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][2][Applets][8][Configuration]
PreloadWeight=10

[Containments][2][Applets][9]
immutability=1
plugin=org.kde.plasma.minimizeall

[Containments][2][Applets][9][Configuration]
PreloadWeight=10

[Containments][2][ConfigDialog]
DialogHeight=84
DialogWidth=1920

[Containments][2][Configuration]
PreloadWeight=10

[Containments][2][General]
AppletOrder=3;4;22;23;5;6;8;9;21

[Containments][7]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.plasma.private.systemtray
wallpaperplugin=org.kde.image

[Containments][7][Applets][10]
immutability=1
plugin=org.kde.plasma.volume

[Containments][7][Applets][10][Configuration]
PreloadWeight=10

[Containments][7][Applets][11]
immutability=1
plugin=org.kde.plasma.clipboard

[Containments][7][Applets][11][Configuration]
PreloadWeight=10

[Containments][7][Applets][12]
immutability=1
plugin=org.kde.plasma.devicenotifier

[Containments][7][Applets][12][Configuration]
PreloadWeight=10

[Containments][7][Applets][13]
immutability=1
plugin=org.kde.kdeconnect

[Containments][7][Applets][13][Configuration]
PreloadWeight=10

[Containments][7][Applets][14]
immutability=1
plugin=org.kde.plasma.keyboardindicator

[Containments][7][Applets][14][Configuration]
PreloadWeight=10

[Containments][7][Applets][15]
immutability=1
plugin=org.kde.plasma.nightcolorcontrol

[Containments][7][Applets][15][Configuration]
PreloadWeight=10

[Containments][7][Applets][16]
immutability=1
plugin=org.kde.plasma.notifications

[Containments][7][Applets][16][Configuration]
PreloadWeight=10

[Containments][7][Applets][17]
immutability=1
plugin=org.kde.plasma.printmanager

[Containments][7][Applets][17][Configuration]
PreloadWeight=10

[Containments][7][Applets][18]
immutability=1
plugin=org.kde.plasma.vault

[Containments][7][Applets][18][Configuration]
PreloadWeight=10

[Containments][7][Applets][19]
immutability=1
plugin=org.kde.plasma.networkmanagement

[Containments][7][Applets][19][Configuration]
PreloadWeight=10

[Containments][7][Applets][20]
immutability=1
plugin=org.kde.plasma.battery

[Containments][7][Applets][20][Configuration]
PreloadWeight=10

[Containments][7][Configuration]
PreloadWeight=10

[Containments][7][General]
extraItems=org.kde.plasma.bluetooth,org.kde.kdeconnect,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.notifications,org.kde.plasma.volume,org.kde.plasma.vault,org.kde.plasma.keyboardindicator,org.kde.plasma.nightcolorcontrol,org.kde.plasma.printmanager,org.kde.plasma.networkmanagement
knownItems=org.kde.plasma.bluetooth,org.kde.kdeconnect,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.notifications,org.kde.plasma.volume,org.kde.plasma.vault,org.kde.plasma.keyboardindicator,org.kde.plasma.nightcolorcontrol,org.kde.plasma.printmanager,org.kde.plasma.networkmanagement

[ScreenMapping]
itemsOnDisabledScreens=
EOF


# ====== Window Manager configuration =======================================

# ------ Set global theme ---------------------------------------------------
cat >/home/${USER_NAME}/.config/kwinrc <<EOF
[TabBox]
DesktopLayout=org.kde.breeze.desktop
DesktopListLayout=org.kde.breeze.desktop
LayoutName=org.kde.breeze.desktop

[org.kde.kdecoration2]
library=org.kde.oxygen
theme=Oxygen
EOF


# ------ Set Plasma style ---------------------------------------------------
cat >/home/${USER_NAME}/.config/plasmarc <<EOF
[Theme]
name=air
EOF


# ------ Set KSplash theme --------------------------------------------------
cat >/home/${USER_NAME}/.config/ksplashrc <<EOF
[KSplash]
Engine=KSplashQML
Theme=org.kde.breeze.desktop
EOF


# ------ Set mouse cursor theme ---------------------------------------------
cat >/home/${USER_NAME}/.config/kcminputrc <<EOF
[Mouse]
cursorTheme=breeze_cursors
EOF


# ------ Set global KDE settings --------------------------------------------
# Includes: icons theme and colours
cat >/home/${USER_NAME}/.config/kdeglobals <<EOF
[\$Version]
update_info=filepicker.upd:filepicker-remove-old-previews-entry,fonts_global.upd:Fonts_Global,fonts_global_toolbar.upd:Fonts_Global_Toolbar,icons_remove_effects.upd:IconsRemoveEffects,kwin.upd:animation-speed

[ColorEffects:Disabled]
ChangeSelectionColor=
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
Enable=
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=-0.9
ColorEffect=1
ContrastAmount=0.25
ContrastEffect=2
Enable=true
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=224,223,222
BackgroundNormal=223,220,217
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=146,76,157
ForegroundInactive=137,136,135
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=34,31,30
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[Colors:Complementary]
BackgroundAlternate=196,224,255
BackgroundNormal=24,21,19
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=255,128,224
ForegroundInactive=137,136,135
ForegroundLink=88,172,255
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=231,253,255
ForegroundPositive=0,110,40
ForegroundVisited=150,111,232

[Colors:Selection]
BackgroundAlternate=62,138,204
BackgroundNormal=67,172,232
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=108,36,119
ForegroundInactive=199,226,248
ForegroundLink=0,49,110
ForegroundNegative=156,14,14
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=69,40,134

[Colors:Tooltip]
BackgroundAlternate=196,224,255
BackgroundNormal=24,21,19
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=255,128,224
ForegroundInactive=137,136,135
ForegroundLink=88,172,255
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=231,253,255
ForegroundPositive=0,110,40
ForegroundVisited=150,111,232

[Colors:View]
BackgroundAlternate=248,247,246
BackgroundNormal=255,255,255
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=146,76,157
ForegroundInactive=137,136,135
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=31,28,27
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[Colors:Window]
BackgroundAlternate=218,217,216
BackgroundNormal=214,210,208
DecorationFocus=58,167,221
DecorationHover=110,214,255
ForegroundActive=146,76,157
ForegroundInactive=137,136,135
ForegroundLink=0,87,174
ForegroundNegative=191,3,3
ForegroundNeutral=176,128,0
ForegroundNormal=34,31,30
ForegroundPositive=0,110,40
ForegroundVisited=100,74,155

[General]
ColorScheme=Oxygen
Name=Breeze
shadeSortColumn=true
widgetStyle=Breeze

[Icons]
Theme=oxygen

[KDE]
ColorScheme=Breeze
LookAndFeelPackage=org.kde.breeze.desktop
contrast=4
widgetStyle=Oxygen

[KFileDialog Settings]
Allow Expansion=false
Automatically select filename extension=true
Breadcrumb Navigation=true
Decoration position=2
LocationCombo Completionmode=5
PathCombo Completionmode=5
Show Bookmarks=false
Show Full Path=false
Show Inline Previews=true
Show Preview=false
Show Speedbar=true
Show hidden files=false
Sort by=Name
Sort directories first=true
Sort reversed=false
Speedbar Width=138
View Style=DetailTree

[WM]
activeBackground=48,174,232
activeBlend=252,252,252
activeForeground=255,255,255
inactiveBackground=224,223,222
inactiveBlend=75,71,67
inactiveForeground=75,71,67
EOF


# ====== Keyboard configuration =============================================
cat >/home/${USER_NAME}/.config/kxkbrc <<EOF
[Layout]
DisplayNames=,,
LayoutList=de(nodeadkeys),no,us
LayoutLoopCount=-1
Model=pc105
ResetOldOptions=false
ShowFlag=true
ShowLabel=false
ShowLayoutIndicator=true
ShowSingle=false
SwitchMode=Global
Use=true
EOF


# ====== Konsole configuration ==============================================
mkdir -p /home/${USER_NAME}/.local/share/kxmlgui5/konsole

cat >/home/${USER_NAME}/.local/share/kxmlgui5/konsole/konsoleui.rc <<EOF
<!DOCTYPE kpartgui>
<kpartgui name="konsole" version="11">
 <MenuBar>
  <Menu name="file">
   <text>File</text>
   <Action name="new-window"/>
   <Action name="new-tab"/>
   <Action name="clone-tab"/>
   <Separator/>
   <DefineGroup name="session-operations"/>
   <Separator/>
   <DefineGroup name="session-tab-operations"/>
   <Action name="close-window"/>
  </Menu>
  <Menu name="edit">
   <text>Edit</text>
   <DefineGroup name="session-edit-operations"/>
  </Menu>
  <Menu name="view">
   <text>View</text>
   <Menu name="view-split">
    <text>Split View</text>
    <Action name="split-view-left-right"/>
    <Action name="split-view-top-bottom"/>
    <Action name="close-active-view"/>
    <Action name="close-other-views"/>
    <Action name="expand-active-view"/>
    <Action name="shrink-active-view"/>
   </Menu>
   <Separator/>
   <Action name="detach-tab"/>
   <Action name="detach-view"/>
   <Separator/>
   <DefineGroup name="session-view-operations"/>
  </Menu>
  <Action name="bookmark"/>
  <Menu name="settings">
   <text>Settings</text>
   <DefineGroup name="session-settings"/>
   <Action name="manage-profiles"/>
   <Action name="show-menubar"/>
   <Separator/>
   <Action name="view-full-screen"/>
   <Separator/>
   <Action name="configure-shortcuts"/>
   <Action name="configure-notifications"/>
   <Action name="configure-settings"/>
  </Menu>
  <Menu name="help">
   <text>Help</text>
  </Menu>
 </MenuBar>
 <ActionProperties scheme="Default">
  <Action name="clone-tab" shortcut=""/>
  <Action name="help_contents" shortcut=""/>
  <Action name="options_configure" shortcut=""/>
 </ActionProperties>
</kpartgui>
EOF


cat >/home/${USER_NAME}/.local/share/kxmlgui5/konsole/sessionui.rc <<EOF
<!DOCTYPE kpartgui>
<kpartgui name="session" version="27">
 <MenuBar>
  <Menu name="file">
   <Action name="file_save_as" group="session-operations"/>
   <Separator group="session-operations"/>
   <Action name="file_print" group="session-operations"/>
   <Separator group="session-operations"/>
   <Action name="open-browser" group="session-operations"/>
   <Action name="close-session" group="session-tab-operations"/>
  </Menu>
  <Menu name="edit">
   <Action name="edit_copy" group="session-edit-operations"/>
   <Action name="edit_paste" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="select-all" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="copy-input-to" group="session-edit-operations"/>
   <Action name="send-signal" group="session-edit-operations"/>
   <Action name="rename-session" group="session-edit-operations"/>
   <Action name="zmodem-upload" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="edit_find" group="session-edit-operations"/>
   <Action name="edit_find_next" group="session-edit-operations"/>
   <Action name="edit_find_prev" group="session-edit-operations"/>
  </Menu>
  <Menu name="view">
   <Action name="monitor-silence" group="session-view-operations"/>
   <Action name="monitor-activity" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="view-readonly" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="enlarge-font" group="session-view-operations"/>
   <Action name="reset-font-size" group="session-view-operations"/>
   <Action name="shrink-font" group="session-view-operations"/>
   <Action name="set-encoding" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="clear-history" group="session-view-operations"/>
   <Action name="clear-history-and-reset" group="session-view-operations"/>
  </Menu>
  <Menu name="settings">
   <Action name="edit-current-profile" group="session-settings"/>
   <Action name="switch-profile" group="session-settings"/>
  </Menu>
 </MenuBar>
 <Menu name="session-popup-menu">
  <Action name="edit_copy"/>
  <Action name="edit_paste"/>
  <Action name="web-search"/>
  <Action name="open-browser"/>
  <Separator/>
  <Action name="set-encoding"/>
  <Action name="clear-history"/>
  <Action name="adjust-history"/>
  <Separator/>
  <Action name="view-readonly"/>
  <Action name="switch-profile"/>
  <Action name="edit-current-profile"/>
 </Menu>
 <ActionProperties scheme="Default">
  <Action name="copy-input-to-none" shortcut="Ctrl+_"/>
  <Action name="copy-input-to-all-tabs" shortcut="Ctrl+;"/>
 </ActionProperties>
</kpartgui>
EOF


mkdir -p /home/${USER_NAME}/.local/share/konsole

cat >/home/${USER_NAME}/.local/share/konsole/Profile\ 1.profile <<EOF
[Appearance]
ColorScheme=BlackOnLightYellow

[General]
Name=Profile 1
Parent=FALLBACK/
EOF


cat >/home/${USER_NAME}/.config/konsolerc <<EOF
[Desktop Entry]
DefaultProfile=Profile 1.profile
EOF


cat >/home/${USER_NAME}/.config/katerc <<EOF
[General]
Close After Last=false
Config Revision=10
Days Meta Infos=30
Modified Notification=false
Quick Open List Mode=0
Quick Open Search Mode=0
Recent File List Entry Count=10
Restore Window Configuration=true
Save Meta Infos=true
Show Full Path in Title=false
Show Menu Bar=true
Show Status Bar=true
Show Tab Bar=true
Startup Session=manual

[KTextEditor Document]
Allow End of Line Detection=true
BOM=false
Backup Local=false
Backup Prefix=
Backup Remote=false
Backup Suffix=~
Encoding=UTF-8
End of Line=0
Indent On Backspace=true
Indent On Tab=true
Indent On Text Paste=false
Indentation Mode=normal
Indentation Width=1
Keep Extra Spaces=false
Line Length Limit=10000
Newline at End of File=true
On-The-Fly Spellcheck=false
Overwrite Mode=false
PageUp/PageDown Moves Cursor=false
Remove Spaces=1
ReplaceTabsDyn=true
Show Spaces=0
Show Tabs=true
Smart Home=true
Swap Directory=
Swap File Mode=1
Swap Sync Interval=15
Tab Handling=2
Tab Width=3
Trailing Marker Size=1
Word Wrap=false
Word Wrap Column=80

[KTextEditor Editor]
Encoding Prober Type=1
Fallback Encoding=ISO 8859-15

[KTextEditor Renderer]
Animate Bracket Matching=false
Schema=Normal
Show Indentation Lines=false
Show Whole Bracket Expression=false
Word Wrap Marker=false

[KTextEditor View]
Allow Mark Menu=true
Auto Brackets=false
Auto Center Lines=0
Auto Completion=true
Backspace Remove Composed Characters=false
Bookmark Menu Sorting=0
Chars To Enclose Selection=
Default Mark Type=1
Dynamic Word Wrap=true
Dynamic Word Wrap Align Indent=80
Dynamic Word Wrap At Static Marker=false
Dynamic Word Wrap Indicators=1
Dynamic Wrap not at word boundaries=false
Fold First Line=false
Folding Bar=true
Folding Preview=true
Icon Bar=false
Input Mode=0
Keyword Completion=true
Line Modification=true
Line Numbers=true
Maximum Search History Size=100
Mouse Paste At Cursor Position=false
Persistent Selection=false
Scroll Bar Marks=false
Scroll Bar Mini Map All=true
Scroll Bar Mini Map Width=60
Scroll Bar MiniMap=true
Scroll Bar Preview=true
Scroll Past End=false
Search/Replace Flags=140
Show Line Count=false
Show Scrollbars=0
Show Word Count=false
Smart Copy Cut=false
Text Drag And Drop=true
User Sets Of Chars To Enclose Selection=
Vi Input Mode Steal Keys=false
Vi Relative Line Numbers=false
Word Completion=true
Word Completion Minimal Word Length=3
Word Completion Remove Tail=true

[Konsole]
AutoSyncronize=true
RemoveExtension=false
RunPrefix=
SetEditor=false
EOF


# ====== SDDM ===============================================================
mkdir -p /etc/sddm.conf.d

cat >/etc/sddm.conf.d/kde_settings.conf <<EOF
[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=
RebootCommand=

[Theme]
Current=breeze

[Users]
MaximumUid=60000
MinimumUid=1000
EOF


mkdir -p /usr/share/sddm/themes/breeze

cat >/usr/share/sddm/themes/breeze/theme.conf.user  <<EOF
[General]
background=${BACKGROUND_SDDM}
type=image
EOF


# ====== Fix permissions ====================================================
chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config
chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local
