#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -x


# ###### NorNet configuration ###############################################

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt ] ; then
   /usr/bin/apt-get update
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y nornet-management nornet-autoupdate

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y nornet-management nornet-autoupdate
fi


# ###### Prepare source repositories ########################################

# NOTE: The repositories are not cloned here!

sudo -u nornetpp mkdir -p /home/nornetpp/src/nornet-control
cd /home/nornetpp/src/nornet-control
sudo -u nornetpp git init
sudo -u nornetpp git remote add origin https://github.com/simula/nornet-control.git

cd /home/nornetpp
sudo -u nornetpp ln -s src/nornet-control/src ctrl
