#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


USER_NAME=nornetpp



# ###### NorNet development configuration ###################################

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then
   /usr/bin/apt-get update
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y nornet-display sddm \
      kde-style-oxygen-qt5 gtk2-engines-oxygen \
      plasma-theme-oxygen oxygen-cursor-theme oxygen-cursor-theme-extra oxygen-icon-theme oxygen-sounds

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y nornet-display
fi


# ====== Make directories ===================================================
mkdir -p /home/${USER_NAME}/.config
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config
mkdir -p /home/${USER_NAME}/.local
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local


# ====== Desktop configuration ==============================================
cat >/home/${USER_NAME}/.config/kscreenlockerrc <<EOF
[$Version]
update_info=kscreenlocker.upd:0.1-autolock

[Greeter][Wallpaper][org.kde.image][General]
Image=file:///usr/share/nornet-desktop/Desktop-without-Logo/Display1-3840x2160-plain.jpeg
EOF
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/kscreenlockerrc


cat >/home/${USER_NAME}/.config/kactivitymanagerdrc <<EOF
[activities]
6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788=Default

[main]
currentActivity=6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788
EOF
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/kactivitymanagerdrc


cat >/home/${USER_NAME}/.config/plasma-org.kde.plasma.desktop-appletsrc <<EOF
[ActionPlugins][0]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu
wheel:Vertical;NoModifier=org.kde.switchdesktop

[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
ItemGeometriesHorizontal=
activityId=6ef93fb7-d7a8-49cb-a444-4fa9ec9d9788
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][1][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Configuration]
PreloadWeight=10

[Containments][1][General]
ToolBoxButtonState=topcenter
ToolBoxButtonX=739

[Containments][1][Wallpaper][org.kde.image][General]
Image=file:///usr/share/nornet-desktop/Desktop-without-Logo/Background1-3840x2160-plain.png

[Containments][2]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][2][Applets][21]
immutability=1
plugin=org.kde.plasma.systemloadviewer

[Containments][2][Applets][21][Configuration]
PreloadWeight=42

[Containments][2][Applets][22]
immutability=1
plugin=org.kde.plasma.icon

[Containments][2][Applets][22][Configuration]
PreloadWeight=42
localPath=/home/nornetpp/.local/share/plasma_icons/firefox.desktop
url=file:///usr/share/applications/firefox.desktop

[Containments][2][Applets][23]
immutability=1
plugin=org.kde.plasma.icon

[Containments][2][Applets][23][Configuration]
PreloadWeight=42
localPath=/home/nornetpp/.local/share/plasma_icons/org.kde.konsole.desktop
url=file:///usr/share/applications/org.kde.konsole.desktop

[Containments][2][Applets][3]
immutability=1
plugin=org.kde.plasma.kickoff

[Containments][2][Applets][3][Configuration]
PreloadWeight=92

[Containments][2][Applets][3][Configuration][Configuration/General]
showAppsByName=true

[Containments][2][Applets][3][Configuration][General]
favorites=preferred://browser,org.kde.discover.desktop,org.kde.kontact.desktop,org.kde.kate.desktop,libreoffice-startcenter.desktop,org.kde.dolphin.desktop,org.kde.ksysguard.desktop,systemsettings.desktop,org.kde.konsole.desktop
favoritesPortedToKAstats=true

[Containments][2][Applets][3][Configuration][Shortcuts]
global=Alt+F1

[Containments][2][Applets][3][Shortcuts]
global=Alt+F1

[Containments][2][Applets][4]
immutability=1
plugin=org.kde.plasma.pager

[Containments][2][Applets][4][Configuration]
PreloadWeight=10

[Containments][2][Applets][5]
immutability=1
plugin=org.kde.plasma.taskmanager

[Containments][2][Applets][5][Configuration]
PreloadWeight=10

[Containments][2][Applets][6]
immutability=1
plugin=org.kde.plasma.systemtray

[Containments][2][Applets][6][Configuration]
PreloadWeight=10
SystrayContainmentId=7

[Containments][2][Applets][8]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][2][Applets][8][Configuration]
PreloadWeight=10

[Containments][2][Applets][9]
immutability=1
plugin=org.kde.plasma.minimizeall

[Containments][2][Applets][9][Configuration]
PreloadWeight=10

[Containments][2][ConfigDialog]
DialogHeight=84
DialogWidth=1920

[Containments][2][Configuration]
PreloadWeight=10

[Containments][2][General]
AppletOrder=3;4;22;23;5;6;8;9;21

[Containments][7]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.plasma.private.systemtray
wallpaperplugin=org.kde.image

[Containments][7][Applets][10]
immutability=1
plugin=org.kde.plasma.volume

[Containments][7][Applets][10][Configuration]
PreloadWeight=10

[Containments][7][Applets][11]
immutability=1
plugin=org.kde.plasma.clipboard

[Containments][7][Applets][11][Configuration]
PreloadWeight=10

[Containments][7][Applets][12]
immutability=1
plugin=org.kde.plasma.devicenotifier

[Containments][7][Applets][12][Configuration]
PreloadWeight=10

[Containments][7][Applets][13]
immutability=1
plugin=org.kde.kdeconnect

[Containments][7][Applets][13][Configuration]
PreloadWeight=10

[Containments][7][Applets][14]
immutability=1
plugin=org.kde.plasma.keyboardindicator

[Containments][7][Applets][14][Configuration]
PreloadWeight=10

[Containments][7][Applets][15]
immutability=1
plugin=org.kde.plasma.nightcolorcontrol

[Containments][7][Applets][15][Configuration]
PreloadWeight=10

[Containments][7][Applets][16]
immutability=1
plugin=org.kde.plasma.notifications

[Containments][7][Applets][16][Configuration]
PreloadWeight=10

[Containments][7][Applets][17]
immutability=1
plugin=org.kde.plasma.printmanager

[Containments][7][Applets][17][Configuration]
PreloadWeight=10

[Containments][7][Applets][18]
immutability=1
plugin=org.kde.plasma.vault

[Containments][7][Applets][18][Configuration]
PreloadWeight=10

[Containments][7][Applets][19]
immutability=1
plugin=org.kde.plasma.networkmanagement

[Containments][7][Applets][19][Configuration]
PreloadWeight=10

[Containments][7][Applets][20]
immutability=1
plugin=org.kde.plasma.battery

[Containments][7][Applets][20][Configuration]
PreloadWeight=10

[Containments][7][Configuration]
PreloadWeight=10

[Containments][7][General]
extraItems=org.kde.plasma.bluetooth,org.kde.kdeconnect,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.notifications,org.kde.plasma.volume,org.kde.plasma.vault,org.kde.plasma.keyboardindicator,org.kde.plasma.nightcolorcontrol,org.kde.plasma.printmanager,org.kde.plasma.networkmanagement
knownItems=org.kde.plasma.bluetooth,org.kde.kdeconnect,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.notifications,org.kde.plasma.volume,org.kde.plasma.vault,org.kde.plasma.keyboardindicator,org.kde.plasma.nightcolorcontrol,org.kde.plasma.printmanager,org.kde.plasma.networkmanagement

[ScreenMapping]
itemsOnDisabledScreens=
EOF
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/plasma-org.kde.plasma.desktop-appletsrc


# ====== Window Manager configuration =======================================
cat >/home/${USER_NAME}/.config/kwinrc <<EOF
[Desktops]
Number=4
Rows=2

[org.kde.kdecoration2]
library=org.kde.oxygen
theme=Breeze
EOF
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/kwinrc


# ====== Keyboard configuration =============================================
mkdir -p /home/${USER_NAME}/.config
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config

cat >/home/${USER_NAME}/.config/kxkbrc <<EOF
[Layout]
DisplayNames=,,
LayoutList=de(nodeadkeys),no,us
LayoutLoopCount=-1
Model=pc105
ResetOldOptions=false
ShowFlag=true
ShowLabel=false
ShowLayoutIndicator=true
ShowSingle=false
SwitchMode=Global
Use=true
EOF

chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/kxkbrc


# ====== Konsole configuration ==============================================
mkdir -p /home/${USER_NAME}/.local/share/kxmlgui5/konsole
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local/share/kxmlgui5/konsole

cat >/home/${USER_NAME}/.local/share/kxmlgui5/konsole/konsoleui.rc <<EOF
<!DOCTYPE kpartgui>
<kpartgui name="konsole" version="11">
 <MenuBar>
  <Menu name="file">
   <text>File</text>
   <Action name="new-window"/>
   <Action name="new-tab"/>
   <Action name="clone-tab"/>
   <Separator/>
   <DefineGroup name="session-operations"/>
   <Separator/>
   <DefineGroup name="session-tab-operations"/>
   <Action name="close-window"/>
  </Menu>
  <Menu name="edit">
   <text>Edit</text>
   <DefineGroup name="session-edit-operations"/>
  </Menu>
  <Menu name="view">
   <text>View</text>
   <Menu name="view-split">
    <text>Split View</text>
    <Action name="split-view-left-right"/>
    <Action name="split-view-top-bottom"/>
    <Action name="close-active-view"/>
    <Action name="close-other-views"/>
    <Action name="expand-active-view"/>
    <Action name="shrink-active-view"/>
   </Menu>
   <Separator/>
   <Action name="detach-tab"/>
   <Action name="detach-view"/>
   <Separator/>
   <DefineGroup name="session-view-operations"/>
  </Menu>
  <Action name="bookmark"/>
  <Menu name="settings">
   <text>Settings</text>
   <DefineGroup name="session-settings"/>
   <Action name="manage-profiles"/>
   <Action name="show-menubar"/>
   <Separator/>
   <Action name="view-full-screen"/>
   <Separator/>
   <Action name="configure-shortcuts"/>
   <Action name="configure-notifications"/>
   <Action name="configure-settings"/>
  </Menu>
  <Menu name="help">
   <text>Help</text>
  </Menu>
 </MenuBar>
 <ActionProperties scheme="Default">
  <Action name="clone-tab" shortcut=""/>
  <Action name="help_contents" shortcut=""/>
  <Action name="options_configure" shortcut=""/>
 </ActionProperties>
</kpartgui>
EOF

chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local/share/kxmlgui5/konsole/konsoleui.rc


cat >/home/${USER_NAME}/.local/share/kxmlgui5/konsole/sessionui.rc <<EOF
<!DOCTYPE kpartgui>
<kpartgui name="session" version="27">
 <MenuBar>
  <Menu name="file">
   <Action name="file_save_as" group="session-operations"/>
   <Separator group="session-operations"/>
   <Action name="file_print" group="session-operations"/>
   <Separator group="session-operations"/>
   <Action name="open-browser" group="session-operations"/>
   <Action name="close-session" group="session-tab-operations"/>
  </Menu>
  <Menu name="edit">
   <Action name="edit_copy" group="session-edit-operations"/>
   <Action name="edit_paste" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="select-all" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="copy-input-to" group="session-edit-operations"/>
   <Action name="send-signal" group="session-edit-operations"/>
   <Action name="rename-session" group="session-edit-operations"/>
   <Action name="zmodem-upload" group="session-edit-operations"/>
   <Separator group="session-edit-operations"/>
   <Action name="edit_find" group="session-edit-operations"/>
   <Action name="edit_find_next" group="session-edit-operations"/>
   <Action name="edit_find_prev" group="session-edit-operations"/>
  </Menu>
  <Menu name="view">
   <Action name="monitor-silence" group="session-view-operations"/>
   <Action name="monitor-activity" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="view-readonly" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="enlarge-font" group="session-view-operations"/>
   <Action name="reset-font-size" group="session-view-operations"/>
   <Action name="shrink-font" group="session-view-operations"/>
   <Action name="set-encoding" group="session-view-operations"/>
   <Separator group="session-view-operations"/>
   <Action name="clear-history" group="session-view-operations"/>
   <Action name="clear-history-and-reset" group="session-view-operations"/>
  </Menu>
  <Menu name="settings">
   <Action name="edit-current-profile" group="session-settings"/>
   <Action name="switch-profile" group="session-settings"/>
  </Menu>
 </MenuBar>
 <Menu name="session-popup-menu">
  <Action name="edit_copy"/>
  <Action name="edit_paste"/>
  <Action name="web-search"/>
  <Action name="open-browser"/>
  <Separator/>
  <Action name="set-encoding"/>
  <Action name="clear-history"/>
  <Action name="adjust-history"/>
  <Separator/>
  <Action name="view-readonly"/>
  <Action name="switch-profile"/>
  <Action name="edit-current-profile"/>
 </Menu>
 <ActionProperties scheme="Default">
  <Action name="copy-input-to-none" shortcut="Ctrl+_"/>
  <Action name="copy-input-to-all-tabs" shortcut="Ctrl+;"/>
 </ActionProperties>
</kpartgui>
EOF

chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local/share/kxmlgui5/konsole/sessionui.rc


mkdir -p /home/${USER_NAME}/.local/share/konsole

cat >/home/${USER_NAME}/.local/share/konsole/Profile\ 1.profile <<EOF
[Appearance]
ColorScheme=BlackOnLightYellow

[General]
Name=Profile 1
Parent=FALLBACK/
EOF

chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local/share/konsole/Profile\ 1.profile


cat >/home/${USER_NAME}/.config/konsolerc <<EOF
[Desktop Entry]
DefaultProfile=Profile 1.profile
EOF

chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.config/konsolerc
