#!/bin/bash -ex
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Set timezone #######################################################
timedatectl set-timezone Europe/Oslo


# ###### Renew SSH keys and enforce strong cipher configurations ############
if [ -e /usr/bin/Create-New-SSH-Node-Keys ] ; then
   /usr/bin/Create-New-SSH-Node-Keys -yes-to-all-i-am-really-sure
fi


# ###### Make some additions to .bashrc #####################################
cat >>/home/nornetpp/.bashrc <<EOF


# ---------------------------------------------------------------------------

alias runws="sudo echo Starting Wireshark && ( sudo wireshark & )"

ulimit -c unlimited

export EDITOR=joe
export CVSEDITOR=\${EDITOR}
export SVN_EDITOR=\${EDITOR}

cores=\`getconf _NPROCESSORS_ONLN 2>/dev/null || true\`
if [ \$cores -gt 1 ] ; then
   export MAKEFLAGS=-j\${cores}
fi
EOF


# ###### Make some directories ##############################################
sudo -u nornetpp mkdir -p /home/nornetpp/src
sudo -u nornetpp chattr +c /home/nornetpp/src
sudo -u nornetpp mkdir -p /home/nornetpp/tmp

sudo -u nornetpp mkdir -p /home/nornetpp/.ssh
sudo -u nornetpp chmod 700 /home/nornetpp/.ssh
sudo -u nornetpp touch /home/nornetpp/.ssh/authorized_keys
sudo -u nornetpp chmod 600 /home/nornetpp/.ssh/authorized_keys
