#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ###### Set timezone #######################################################
timedatectl set-timezone Europe/Oslo


# ###### Make some additions to .bashrc #####################################
cat >>/home/nornetpp/.bashrc <<EOF


# ---------------------------------------------------------------------------

alias runws="sudo echo Starting Wireshark && ( sudo wireshark & )"

ulimit -c unlimited

export EDITOR=joe
export CVSEDITOR=\${EDITOR}
export SVN_EDITOR=\${EDITOR}

cores=\`getconf _NPROCESSORS_ONLN 2>/dev/null || true\`
if [ \$cores -gt 1 ] ; then
   export MAKEFLAGS=-j\${cores}
fi
EOF


# ###### Make some directories ##############################################
sudo -u nornetpp mkdir -p /home/nornetpp/src
sudo -u nornetpp chattr +c /home/nornetpp/src
sudo -u nornetpp mkdir -p /home/nornetpp/tmp

sudo -u nornetpp mkdir -p /home/nornetpp/.ssh
sudo -u nornetpp chmod 700 /home/nornetpp/.ssh
sudo -u nornetpp touch /home/nornetpp/.ssh/authorized_keys
sudo -u nornetpp chmod 600 /home/nornetpp/.ssh/authorized_keys


# ###### Development configuration ##########################################
if [ -e /etc/apt/sources.list ] ; then
   for list in /etc/apt/sources.list `find /etc/apt/sources.list.d -name "*.list"`; do
      cat ${list} | grep "^deb \(.*\)$" | sed -e "s/deb[ \t]*//g" | xargs -n1 -i§ echo "s@^#[ \t]*deb-src \(§\)[ \t]*\$@deb-src \\1@g" >${list}.sed
      cat ${list} | sed -f ${list}.sed >${list}.new
      diff ${list} ${list}.new
      mv ${list}.new ${list}
      rm -f ${list}.sed
   done

   # Add commented-out debugging symbols repository:
   (
      echo ""
      echo "# Ubuntu debugging symbols repositories:"
      echo "# deb http://ddebs.ubuntu.com ${codename} main restricted universe multiverse"
      echo "# deb http://ddebs.ubuntu.com ${codename}-updates main restricted universe multiverse"
      echo "# deb http://ddebs.ubuntu.com ${codename}-proposed main restricted universe multiverse"
   ) >>/etc/apt/sources.list
   apt install ubuntu-dbgsym-keyring || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622

   # Add commented-out MPTCP repository:
   codename=`lsb_release -c -s`
   (
      echo ""
      echo "# Thomas Dreibholz's MPTCP kernel repository:"
      echo "# deb https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} ${codename}-kernel"
      echo "# deb-src https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} ${codename}-kernel"
   ) >>/etc/apt/sources.list

   # Clean up old installer files:
   rm -f /etc/apt/sources.list.curtin.old /etc/apt/sources.list.save
fi


# ###### Renew SSH keys and enforce strong cipher configurations ############
if [ -e /usr/bin/Create-New-SSH-Node-Keys ] ; then
   /usr/bin/Create-New-SSH-Node-Keys -yes-to-all-i-am-really-sure
fi
