#!/bin/bash

IMAGES=`find /vservers -maxdepth 1 -name 'Ubuntu-5gVINNI-*.qcow2'`


echo "------ Commands ------"
for image in ${IMAGES} ; do
   imageFile=`basename ${image}`
   imageName=`echo "${imageFile}" | sed -e "s/\.qcow2//g"`
   echo "image delete Template-${imageName}"
   echo "image create Template-${imageName} --file images/${imageFile} --disk-format qcow2 --container-format bare --public"
   echo "image set --property architecture=amd64 Template-${imageName}"
done
echo "----------------------"

rsync -e "ssh -J oesthorn.nntb.no" -Pav \
   ${IMAGES} nornetpp@odin.simula.nornet:images/
