#!/usr/bin/env bash
#
# Copy Images to OpenStack Controller
# Copyright (C) 2019-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

IMAGES=`find /vservers -maxdepth 1 -name 'Ubuntu-5gVINNI-*.qcow2'`
DESTINATION="nornetpp@odin.simula.nornet:images/"
SSH_PROXY="128.39.37.188"

echo "------ Commands ------"
for image in ${IMAGES} ; do
   imageFile=`basename ${image}`
   imageName=`echo "${imageFile}" | sed -e "s/\.qcow2//g"`
   echo "image delete Template-${imageName}"
   echo "image create Template-${imageName} --file images/${imageFile} --disk-format qcow2 --container-format bare --public"
   echo "image set --property architecture=amd64 Template-${imageName}"
done
echo "----------------------"

rsync -e "ssh -J ${SSH_PROXY}" -Pav --partial \
   ${IMAGES} "${DESTINATION}"
